name: 'Action to deploy stacks to portainer'
description: 'Action to deploy stacks to portainer'
outputs:
  saida:
    description: "success in deploy"
    value: ''
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/stack.sh
      shell: bash
