name: 'Hello World'
description: 'Greet someone'
inputs:
  name:  
    description: 'name'
    required: true
  stack:  
    description: 'stack'
    required: true
outputs:
  random-number:
    description: "saida do deploy"
    value: deployada
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
